# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ex1' do
 
  pod 'React', :path => '../node_modules/react-native'
  pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'
  

  target 'ex1-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ex1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

